const $=s=>document.querySelector(s);const promptEl=$("#prompt"),send=$("#send"),attach=$("#attach"),file=$("#file"),filesEl=$("#files"),journey=$("#journey"),intro=$("#intro"),status=$("#status"),provider=$("#provider"),historyEl=$("#history");let files=[];let lastInput="";
attach.onclick=()=>file.click();file.onchange=()=>{addFiles([...file.files]);file.value=""};
document.addEventListener("paste",e=>{const imgs=[...e.clipboardData.items].filter(i=>i.type.startsWith("image/")).map(i=>i.getAsFile()).filter(Boolean);if(imgs.length){e.preventDefault();addFiles(imgs)}});
["dragenter","dragover"].forEach(x=>document.addEventListener(x,e=>{if(e.dataTransfer?.files?.length){e.preventDefault();document.body.classList.add("drag")}}));document.addEventListener("drop",e=>{document.body.classList.remove("drag");if(e.dataTransfer?.files?.length){e.preventDefault();addFiles([...e.dataTransfer.files])}});document.addEventListener("dragleave",()=>document.body.classList.remove("drag"));
function addFiles(a){files.push(...a);renderFiles()}function renderFiles(){filesEl.innerHTML=files.map((f,i)=>'<div class="file-chip">📎 '+esc(f.name)+' <button data-i="'+i+'">×</button></div>').join("");filesEl.querySelectorAll("button").forEach(b=>b.onclick=()=>{files.splice(+b.dataset.i,1);renderFiles()})}
promptEl.addEventListener("input",()=>{promptEl.style.height="auto";promptEl.style.height=Math.min(promptEl.scrollHeight,150)+"px"});promptEl.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();run()}});
$("#newBtn").onclick=()=>{files=[];renderFiles();journey.className="journey hidden";journey.innerHTML="";intro.classList.remove("hidden");promptEl.value="";status.textContent="Sẵn sàng"};
$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");
const apiKeyBtn=document.createElement("button");apiKeyBtn.id="apiKeyBtn";apiKeyBtn.className="key-btn";apiKeyBtn.textContent="🔑 API key";document.querySelector(".side-foot").prepend(apiKeyBtn);
apiKeyBtn.onclick=openKeyDialog;
function keyStorageName(){return "khamphagiaitoan_api_key_"+provider.value}
function getApiKey(){return localStorage.getItem(keyStorageName())||""}
function refreshKeyButton(){apiKeyBtn.textContent=getApiKey()?"🔑 Đã có API key":"🔑 Nhập API key"}
provider.onchange=refreshKeyButton;refreshKeyButton();
function openKeyDialog(){
 const old=document.querySelector(".key-modal");if(old)old.remove();
 const name=provider.value==="gemini"?"Gemini API key":"OpenAI API key";
 const modal=document.createElement("div");modal.className="key-modal";
 modal.innerHTML='<div class="key-box"><button class="key-close">×</button><div class="eyebrow">CẤU HÌNH AI</div><h3>'+name+'</h3><p>Nhập key của anh để website dùng key riêng cho các lần tạo hành trình. Key được lưu <b>chỉ trên trình duyệt này</b> và gửi qua HTTPS cùng yêu cầu AI; website không hiển thị lại đầy đủ key.</p><input id="keyInput" type="password" autocomplete="off" placeholder="Dán API key vào đây..." value="'+esc(getApiKey())+'"><label class="show-key"><input id="showKey" type="checkbox"> Hiện key</label><div class="key-actions"><button id="keyCancel">Hủy</button><button id="keySave">Lưu trên máy này</button></div></div>';
 document.body.appendChild(modal);
 const input=modal.querySelector("#keyInput");modal.querySelector("#showKey").onchange=e=>input.type=e.target.checked?"text":"password";
 modal.querySelector(".key-close").onclick=()=>modal.remove();modal.querySelector("#keyCancel").onclick=()=>modal.remove();
 modal.querySelector("#keySave").onclick=()=>{const v=input.value.trim();if(v)localStorage.setItem(keyStorageName(),v);else localStorage.removeItem(keyStorageName());refreshKeyButton();modal.remove()};
 input.focus();
}
async function run(){const text=promptEl.value.trim();if(!text&&!files.length)return;lastInput=text;status.textContent="Đang xây hành trình…";send.disabled=true;intro.classList.add("hidden");journey.className="journey";journey.innerHTML='<div class="loading">Đang đọc đề và dựng Hành Trình Khám Phá…</div>';try{const payload={provider:provider.value,prompt:text,files:await encodeFiles(files),apiKey:getApiKey()};const r=await fetch("/api/journey",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||"Không tạo được hành trình");renderJourney(data.journey);addHistory(data.journey?.title||text||"Bài toán mới");status.textContent="Đã tạo hành trình"}catch(e){journey.innerHTML='<div class="error"><b>Không tạo được hành trình.</b><br>'+esc(e.message)+'</div>';status.textContent="Có lỗi"}finally{send.disabled=false}}
async function encodeFiles(a){return Promise.all(a.map(f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:f.name,type:f.type||"application/octet-stream",data:r.result});r.onerror=rej;r.readAsDataURL(f)})))}
function renderJourney(j){const clues=(j.clues||[]).map((c,i)=>'<div class="clue"><b>Manh mối '+(i+1)+': '+esc(c.title||"")+'</b><p>'+esc(c.content||"")+'</p></div>').join("");const qs=(j.exploration?.guiding_questions||[]).map(q=>'<div class="question">❓ '+esc(q)+'</div>').join("");const practices=(j.practice||[]).map((p,i)=>'<div class="practice-item"><b>Bài '+(i+1)+' — '+esc(p.level||"")+'</b><p>'+esc(p.problem||"")+'</p></div>').join("");journey.innerHTML='<div class="journey-head"><div><h2>'+esc(j.title||"Hành Trình Khám Phá Toán")+'</h2><p>'+esc(j.summary||"")+'</p></div></div><div class="tree"><div class="branch"><h3>👨‍🎓 HỌC SINH</h3><ul><li>'+esc(j.student?.grade||"Chọn lớp 6–9")+'</li><li>'+esc(j.student?.topic||"Chọn chủ đề")+'</li><li>'+esc(j.student?.task||"Chọn bài toán")+'</li></ul></div><div class="branch"><h3>👨‍🏫 GIÁO VIÊN</h3><ul><li>'+esc(j.teacher?.lesson_goal||"Mục tiêu bài học")+'</li><li>'+esc(j.teacher?.mystery||"Tạo bí ẩn")+'</li><li>'+esc(j.teacher?.clue_strategy||"Tạo manh mối")+'</li></ul></div></div><div class="flow"><div class="step"><div class="card mystery"><div class="eyebrow">BÍ ẨN · TẠO NHU CẦU</div><h3>❓ '+esc(j.mystery?.title||"")+'</h3><p>'+esc(j.mystery?.context||"")+'</p></div></div><div class="step"><div class="card explore"><div class="eyebrow">🔎 KHÁM PHÁ</div><h3>Manh mối 1 → 2 → 3</h3><div class="clues">'+clues+'</div>'+qs+'</div></div><div class="step"><div class="card standard"><div class="eyebrow">📖 CHUẨN HÓA</div><h3>'+esc(j.standardization?.concept||"Kiến thức cần hình thành")+'</h3><p>'+esc(j.standardization?.knowledge||"")+'</p></div></div><div class="step"><div class="card solution"><div class="eyebrow">✍️ LỜI GIẢI / TRÌNH BÀY</div><h3>'+esc(j.solution?.title||"Lời giải chuẩn")+'</h3><p>'+esc((j.solution?.steps||[]).join("\n"))+'</p></div></div><div class="step"><div class="card practice"><div class="eyebrow">📝 LUYỆN TẬP</div><h3>5 bài theo hành trình</h3><div class="practice-list">'+practices+'</div></div></div><div class="step"><div class="card application"><div class="eyebrow">🎯 VẬN DỤNG</div><h3>'+esc(j.application?.title||"Chuyển giao kiến thức")+'</h3><p>'+esc(j.application?.task||"")+'</p></div></div></div>'}
function addHistory(t){const d=document.createElement("div");d.className="history-item";d.textContent=t.slice(0,38);historyEl.prepend(d)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}