const messages=document.getElementById("messages"),promptEl=document.getElementById("prompt"),fileInput=document.getElementById("fileInput"),attachBtn=document.getElementById("attachBtn"),sendBtn=document.getElementById("sendBtn"),attachmentsEl=document.getElementById("attachments"),newChat=document.getElementById("newChat"),historyEl=document.getElementById("history"),menu=document.getElementById("menu"),sidebar=document.getElementById("sidebar");let files=[];let chat=[];const CHATGPT_URL="https://chatgpt.com/";
attachBtn.onclick=()=>fileInput.click();fileInput.onchange=()=>{addFiles([...fileInput.files]);fileInput.value=""};
document.addEventListener("paste",e=>{const imgs=[...e.clipboardData.items].filter(i=>i.type.startsWith("image/")).map(i=>i.getAsFile()).filter(Boolean);if(imgs.length){e.preventDefault();addFiles(imgs)}});
["dragenter","dragover"].forEach(x=>document.addEventListener(x,e=>{if(e.dataTransfer?.files?.length){e.preventDefault();document.body.classList.add("drop")}}));document.addEventListener("drop",e=>{document.body.classList.remove("drop");if(e.dataTransfer?.files?.length){e.preventDefault();addFiles([...e.dataTransfer.files])}});document.addEventListener("dragleave",()=>document.body.classList.remove("drop"));
function addFiles(list){files.push(...list);renderFiles()}function renderFiles(){attachmentsEl.innerHTML=files.map((f,i)=>'<div class="file-chip">📎 '+esc(f.name)+' <button data-i="'+i+'">×</button></div>').join("");attachmentsEl.querySelectorAll("button").forEach(b=>b.onclick=()=>{files.splice(+b.dataset.i,1);renderFiles()})}
document.querySelectorAll("[data-example]").forEach(b=>b.onclick=()=>{promptEl.value=b.dataset.example;resize();promptEl.focus()});
function openChatGPT(){window.open(CHATGPT_URL,"_blank","noopener,noreferrer")}document.getElementById("openChatGPT").onclick=openChatGPT;document.getElementById("topChatGPT").onclick=openChatGPT;
newChat.onclick=()=>{chat=[];files=[];renderFiles();messages.innerHTML="";showWelcome();historyEl.innerHTML=""};
menu.onclick=()=>sidebar.classList.toggle("open");
function showWelcome(){messages.innerHTML='<div class="welcome"><div class="hero-mark">∑</div><h1>Hôm nay anh muốn khám phá bài toán nào?</h1><p>Đưa đề bài vào đây. Có thể gõ, dán ảnh chụp màn hình hoặc kéo thả tệp.</p><div class="quick-grid"><button data-example="Tôi sẽ gửi một bài toán. Hãy giúp tôi tìm hiểu từ dữ kiện nhỏ nhất, đừng nhảy bước."><span>🔎</span><b>Khám phá từ đầu</b><small>Đi từng manh mối</small></button><button data-example="Hãy giải bài toán này và giải thích thật rõ vì sao phải làm từng bước."><span>🧮</span><b>Giải bài toán</b><small>Hiểu bản chất</small></button></div></div>';document.querySelectorAll("[data-example]").forEach(b=>b.onclick=()=>{promptEl.value=b.dataset.example;resize();promptEl.focus()})}
promptEl.addEventListener("input",resize);function resize(){promptEl.style.height="auto";promptEl.style.height=Math.min(promptEl.scrollHeight,170)+"px"}promptEl.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}});sendBtn.onclick=send;
async function send(){const text=promptEl.value.trim();if(!text&&!files.length)return;const current=[...files];files=[];renderFiles();promptEl.value="";resize();addMessage("user",text,current);chat.push({text,files:current.map(f=>f.name)});saveHistory(text||current.map(f=>f.name).join(", "));showNotice()}
function showNotice(){setTimeout(()=>{addMessage("assistant","Giao diện đã nhận nội dung của anh.\n\nPhiên bản này đang là lớp giao diện riêng — không tự giả mạo hoặc lấy phiên đăng nhập ChatGPT. Khi anh muốn trao đổi với AI, dùng nút “Mở ChatGPT” ở góc trên; cuộc trò chuyện sẽ mở bằng tài khoản ChatGPT của anh trong tab riêng.")},250)}
function addMessage(role,text,fs){const row=document.createElement("div");row.className="msg "+role;const av=role==="assistant"?'<div class="avatar">∑</div>':"";const previews=(fs||[]).map(f=>'<div class="attachment-preview">'+(f.type.startsWith("image/")?'<img src="'+URL.createObjectURL(f)+'">':"📎 ")+'<span>'+esc(f.name)+'</span></div>').join("");row.innerHTML=role==="assistant"?av+'<div class="bubble">'+format(text)+previews+"</div>":'<div class="bubble">'+format(text)+previews+"</div>";messages.appendChild(row);document.getElementById("chatArea").scrollTo({top:document.getElementById("chatArea").scrollHeight,behavior:"smooth"})}
function saveHistory(t){const item=document.createElement("div");item.className="history-item";item.textContent=t.slice(0,34)||"Bài toán mới";historyEl.prepend(item)}function format(s){return esc(s).replace(/\*\*(.*?)\*\*/g,"<b>$1</b>").replace(/\n/g,"<br>")}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}